name: Ejecutar Radar Financiero

on:
  schedule:
    - cron: '15 14 * * 1-5'
  workflow_dispatch:

jobs:
  ejecucion:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4 # <--- Actualizado a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # <--- Actualizado a v5
        with:
          python-version: '3.12'

      - name: Instalar librerias necesarias
        run: pip install alpaca-py pandas scikit-learn requests lxml pytz

      - name: Arrancar el bot
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: python bot.py
